version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    command:
      mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - "./docker/mysql:/docker-entrypoint-initdb.d"
    restart: always
