openapi: 3.0.3
info:
  title: Caluculator Service
  description: Service for adding numbes, a Goa teaser
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /add/{a}/{b}:
    get:
      tags:
      - calc
      summary: add calc
      operationId: calc#add
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 1228682945796019344
          format: int64
        example: 4886963557863946648
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 6642806206162570878
          format: int64
        example: 8723986392256123438
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: integer
                example: 7309877832173772408
                format: int64
              example: 9092197569596372935
  /minus/{a}/{b}:
    get:
      tags:
      - calc
      summary: minus calc
      operationId: calc#minus
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 2937026320033011362
          format: int64
        example: 207017106558923967
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 6001261670528037577
          format: int64
        example: 5850431520333673251
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: integer
                example: 3237209857320107068
                format: int64
              example: 1089204046671954241
components: {}
